import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as Dialog from '@radix-ui/react-dialog';
import * as Tabs from '@radix-ui/react-tabs';
import {motion, AnimatePresence} from 'framer-motion';
import {Activity, BookOpen, CandlestickChart, RefreshCw, ShieldCheck, TrendingDown, TrendingUp, X} from 'lucide-react';
import './styles.css';

const BUILD_COMMIT = import.meta.env.VITE_GIT_COMMIT || 'local';
const BUILD_TIME = import.meta.env.VITE_BUILD_TIME || new Date().toISOString();

const fmtUsd = (v) => Number.isFinite(Number(v)) ? `${Number(v)>0?'+':''}$${Number(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}` : '-';
const cls = (v) => Number(v)>0 ? 'text-emerald-300' : Number(v)<0 ? 'text-rose-300' : 'text-slate-200';
const load = async (n) => fetch(`/data/${n}?v=${Date.now()}`, {cache:'no-store'}).then(r=>{if(!r.ok) throw Error(n); return r.json()});

function App(){
  const [overview,setOverview]=useState(null), [positions,setPositions]=useState([]), [orders,setOrders]=useState([]), [engines,setEngines]=useState([]), [trades,setTrades]=useState([]), [buildMeta,setBuildMeta]=useState(null);
  const [filter,setFilter]=useState('all'), [query,setQuery]=useState(''), [selected,setSelected]=useState(null), [busy,setBusy]=useState(false), [error,setError]=useState('');
  useEffect(()=>{bootstrap(); fetch('/build.json?v='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(setBuildMeta).catch(()=>{}); const id=setInterval(()=>liveRefresh(true),60000); return()=>clearInterval(id)},[]);
  async function bootstrap(){try{const [o,p,ord,e,t]=await Promise.all(['overview.json','positions.json','orders.json','engines.json','trades.json'].map(load)); setOverview(o); setPositions(p.rows||[]); setOrders(ord||[]); setEngines(e||[]); setTrades(t||[])}catch(e){setError(e.message)}}
  async function liveRefresh(silent=false){if(!silent)setBusy(true);try{const live=await fetch(`/api/live?v=${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('live api '+r.status);return r.json()}); const old=Object.fromEntries(positions.map(p=>[p.symbol,p])); setOverview({...overview,...live.overview, generated_at:live.generated_at}); setOrders(live.orders||[]); setPositions((live.positions||[]).map(p=>normalizeLivePosition(p,old)))}catch(e){if(!silent)setError(e.message)}finally{if(!silent)setBusy(false)}}
  const filtered=useMemo(()=>positions.filter(p=>`${p.symbol} ${p.engine_label} ${p.side}`.toLowerCase().includes(query.toLowerCase())).filter(p=>filter==='all'||(filter==='red'?p.unrealized_pl<0:filter==='unprotected'?p.protection!=='protected':p.side===filter)),[positions,filter,query]);
  const losers=positions.filter(p=>p.unrealized_pl<0); const crypto=positions.filter(p=>p.asset_class==='crypto').reduce((a,p)=>a+Math.abs(p.market_value),0); const port=Number(overview?.portfolio_value||1);
  return <div className="min-h-screen bg-[#050713] text-slate-100"><div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_10%_0%,rgba(37,99,235,.35),transparent_34%),radial-gradient(circle_at_90%_10%,rgba(34,211,238,.18),transparent_30%)]"/><main className="mx-auto max-w-[1540px] p-4 md:p-6">
    <header className="mb-5 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><motion.h1 initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="text-3xl font-black tracking-tight md:text-5xl">Trader Command Center</motion.h1><p className="mt-2 text-slate-400">Live-positioner, risk, engine performance och trading diary i ett cockpit-läge.</p></div><div className="flex flex-wrap gap-2"><Pill>{overview?.generated_at?`Data ${new Date(overview.generated_at).toLocaleString()}`:'Laddar data...'}</Pill><Pill>Build {buildMeta?.commit || BUILD_COMMIT} ? {buildMeta?.built_at ? new Date(buildMeta.built_at).toLocaleString() : new Date(BUILD_TIME).toLocaleString()}</Pill><Button onClick={liveRefresh} disabled={busy}><RefreshCw className={busy?'animate-spin':''} size={16}/> Live refresh</Button></div></header>
    {error && <div className="mb-4 rounded-xl border border-rose-500/40 bg-rose-500/10 p-3 text-rose-200">Fel: {error}</div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Kpi label="Portfolio" value={fmtUsd(overview?.portfolio_value)} icon={<Activity/>}/><Kpi label="Open P/L" value={fmtUsd(overview?.daily_pnl)} tone={Number(overview?.daily_pnl)<0?'red':'green'} icon={<TrendingUp/>}/><Kpi label="Positions" value={positions.length}/><Kpi label="Protected" value={`${positions.filter(p=>p.protection==='protected').length}/${positions.length}`} tone="green" icon={<ShieldCheck/>}/><Kpi label="Working orders" value={orders.length}/><Kpi label="Buying power" value={fmtUsd(overview?.buying_power)}/></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[1.12fr_.88fr]"><Card><div className="mb-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><h2 className="text-lg font-bold">Aktiva positioner</h2><span className="text-sm text-slate-400">{positions.filter(p=>p.side==='long').length} long / {positions.filter(p=>p.side==='short').length} short</span></div><div className="mb-4 flex flex-wrap gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Sök symbol / engine..." className="min-w-[240px] rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2 outline-none focus:border-cyan-400"/>{['all','long','short','red','unprotected'].map(f=><Button key={f} active={filter===f} onClick={()=>setFilter(f)}>{f}</Button>)}</div><div className="grid gap-3 md:grid-cols-2 2xl:grid-cols-3"><AnimatePresence>{filtered.map(p=><PositionCard key={p.symbol} p={p} onClick={()=>setSelected(p)}/>)}</AnimatePresence></div></Card><Card><EngineComparison engines={engines}/></Card></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[.9fr_.85fr_1.25fr]"><Card><h2 className="mb-3 text-lg font-bold">Protection orders</h2><DataTable rows={orders.slice(0,12)} cols={['symbol','side','type','stop_price','status']}/></Card><Card><h2 className="mb-3 text-lg font-bold">Risk snapshot</h2><Timeline items={[`${positions.length} live-positioner från Alpaca`,`${positions.filter(p=>p.protection==='protected').length}/${positions.length} skyddade`,`${losers.length} röda positioner, ${fmtUsd(losers.reduce((a,p)=>a+p.unrealized_pl,0))}`,`Crypto exposure ${(crypto/port*100).toFixed(2)}%`]}/></Card><Card><Journal trades={trades} engines={engines}/></Card></section>
  <footer className="mx-auto mt-5 max-w-[1540px] px-4 pb-5 text-xs text-slate-500 md:px-6">Build {buildMeta?.commit || BUILD_COMMIT} ? {buildMeta?.built_at ? new Date(buildMeta.built_at).toLocaleString() : new Date(BUILD_TIME).toLocaleString()} ? Data {overview?.generated_at?new Date(overview.generated_at).toLocaleString():'-'}</footer></main><PositionDialog pos={selected} onOpenChange={(o)=>!o&&setSelected(null)} trades={trades}/></div>
}
function normalizeLivePosition(p, old){const sym=p.symbol, o=old[sym]||{}; return {symbol:sym,side:p.side,qty:Number(p.qty||0),avg_entry_price:Number(p.avg_entry_price||0),current_price:Number(p.current_price||0),market_value:Number(p.market_value||0),cost_basis:Number(p.cost_basis||0),unrealized_pl:Number(p.unrealized_pl||0),unrealized_plpc:Math.round(Number(p.unrealized_plpc||0)*10000)/100,change_today:Math.round(Number(p.change_today||0)*10000)/100,asset_class:p.asset_class,engine:o.engine||'unknown',engine_label:o.engine_label||'unknown',stop_loss:o.stop_loss,take_profit:o.take_profit,opened_at:o.opened_at,protection:o.protection||'unknown',protection_orders:o.protection_orders||0,stop_prices:o.stop_prices||[]}}
function Button({children,active,...props}){return <button {...props} className={`inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm transition ${active?'border-cyan-400 bg-cyan-400/10 text-cyan-100':'border-slate-700 bg-slate-900/70 text-slate-200 hover:border-cyan-400/70'} disabled:opacity-60`}>{children}</button>}
function Pill({children}){return <span className="rounded-xl border border-slate-700 bg-slate-900/70 px-3 py-2 text-sm text-slate-300">{children}</span>}
function Card({children}){return <motion.section initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="rounded-3xl border border-slate-800 bg-slate-950/70 p-4 shadow-2xl shadow-black/30 backdrop-blur">{children}</motion.section>}
function Kpi({label,value,tone='blue',icon}){const colors={blue:'from-blue-500/20',green:'from-emerald-500/20',red:'from-rose-500/20'};return <Card><div className="flex items-start justify-between"><div><div className="text-[11px] uppercase tracking-widest text-slate-500">{label}</div><div className={`mt-2 text-2xl font-black ${tone==='red'?'text-rose-300':tone==='green'?'text-emerald-300':'text-slate-100'}`}>{value}</div></div><div className={`rounded-2xl bg-gradient-to-br ${colors[tone]} to-transparent p-2 text-cyan-200`}>{icon}</div></div></Card>}
function PositionCard({p,onClick}){return <motion.button layout initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} exit={{opacity:0}} onClick={onClick} className="rounded-2xl border border-slate-800 bg-gradient-to-b from-slate-900 to-slate-950 p-4 text-left transition hover:-translate-y-0.5 hover:border-cyan-400/70"><div className="flex justify-between gap-2"><div><div className="text-2xl font-black">{p.symbol}</div><div className="text-sm text-slate-400">{p.engine_label}</div></div><span className={`h-fit rounded-full border px-2 py-1 text-xs ${p.side==='short'?'border-rose-400/40 text-rose-300':'border-emerald-400/40 text-emerald-300'}`}>{p.side}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Mini label="P/L" value={fmtUsd(p.unrealized_pl)} c={cls(p.unrealized_pl)} sub={`${p.unrealized_plpc}%`}/><Mini label="Value" value={fmtUsd(Math.abs(p.market_value))} sub={`qty ${p.qty}`}/><Mini label="Entry → Now" value={`$${Number(p.avg_entry_price).toFixed(2)}`} sub={`$${Number(p.current_price).toFixed(2)}`}/><Mini label="Protection" value={p.protection==='protected'?'Protected':'Missing'} c={p.protection==='protected'?'text-emerald-300':'text-rose-300'} sub={`SL ${p.stop_loss?Number(p.stop_loss).toFixed(2):'-'}`}/></div></motion.button>}
function Mini({label,value,sub,c='text-slate-100'}){return <div className="rounded-xl border border-slate-800 bg-slate-950/80 p-2"><div className="text-[10px] uppercase text-slate-500">{label}</div><div className={`font-bold ${c}`}>{value}</div><div className="text-xs text-slate-500">{sub}</div></div>}
function EngineComparison({engines}){const rows=[...engines].sort((a,b)=>(b.unrealized_pl+b.pnl)-(a.unrealized_pl+a.pnl));return <><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Engine comparison</h2><CandlestickChart className="text-cyan-300"/></div><div className="space-y-3">{rows.map(e=>{const score=Number(e.pnl||0)+Number(e.unrealized_pl||0);return <div key={e.label} className="rounded-2xl border border-slate-800 bg-slate-950/70 p-3"><div className="flex justify-between"><b>{e.label}</b><span className={cls(score)}>{fmtUsd(score)}</span></div><div className="mt-1 text-xs text-slate-400">{e.channel} · {e.cadence} · WR {e.win_rate}% · open {e.open_positions}</div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full ${score>=0?'bg-emerald-400':'bg-rose-400'}`} style={{width:`${Math.min(100,Math.abs(score)/50)}%`}}/></div></div>})}</div></>}
function DataTable({rows,cols}){return <div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{cols.map(c=><th className="border-b border-slate-800 p-2 text-left text-xs uppercase text-slate-500" key={c}>{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{cols.map(c=><td className="border-b border-slate-900 p-2" key={c}>{String(r[c]??'-')}</td>)}</tr>):<tr><td className="p-2 text-slate-500" colSpan={cols.length}>Inga rader</td></tr>}</tbody></table></div>}
function Timeline({items}){return <div className="space-y-3">{items.map((it,i)=><div className="flex items-center gap-3" key={i}><span className="h-2.5 w-2.5 rounded-full bg-cyan-300"/><span className="text-slate-300">{it}</span></div>)}</div>}
function Journal({trades,engines}){return <Tabs.Root defaultValue="trades"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold">Journal & engines</h2><Tabs.List className="flex gap-2"><Tabs.Trigger value="trades" className="rounded-full border border-slate-700 px-3 py-1 text-sm data-[state=active]:border-cyan-400">Trades</Tabs.Trigger><Tabs.Trigger value="engines" className="rounded-full border border-slate-700 px-3 py-1 text-sm data-[state=active]:border-cyan-400">Engines</Tabs.Trigger></Tabs.List></div><Tabs.Content value="trades"><DataTable rows={trades.slice(0,25)} cols={['timestamp','label','symbol','status','pnl']}/></Tabs.Content><Tabs.Content value="engines"><DataTable rows={engines} cols={['label','open_positions','pnl','unrealized_pl','win_rate']}/></Tabs.Content></Tabs.Root>}
function PositionDialog({pos,onOpenChange,trades}){const related=useMemo(()=>pos?trades.filter(t=>t.symbol===pos.symbol).slice(0,8):[],[pos,trades]);return <Dialog.Root open={!!pos} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/70 backdrop-blur-sm"/><Dialog.Content asChild><motion.div initial={{opacity:0,scale:.96,y:12}} animate={{opacity:1,scale:1,y:0}} className="fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[min(980px,94vw)] -translate-x-1/2 -translate-y-1/2 overflow-auto rounded-3xl border border-slate-700 bg-slate-950 p-5 shadow-2xl"><Dialog.Close className="float-right rounded-xl border border-slate-700 p-2 hover:border-cyan-400"><X size={18}/></Dialog.Close>{pos&&<><Dialog.Title className="text-2xl font-black"><span>{pos.symbol}</span> <span className={pos.side==='short'?'text-rose-300':'text-emerald-300'}>{pos.side?.toUpperCase()}</span></Dialog.Title><p className="text-slate-400">{pos.engine_label}</p><div className="mt-4 grid gap-2 md:grid-cols-4"><Mini label="Entry" value={`$${Number(pos.avg_entry_price).toFixed(4)}`}/><Mini label="Current" value={`$${Number(pos.current_price).toFixed(4)}`}/><Mini label="Open P/L" value={fmtUsd(pos.unrealized_pl)} c={cls(pos.unrealized_pl)} sub={`${pos.unrealized_plpc}%`}/><Mini label="SL / TP" value={`${pos.stop_loss?Number(pos.stop_loss).toFixed(2):'-'} / ${pos.take_profit?Number(pos.take_profit).toFixed(2):'-'}`}/></div><Chart pos={pos}/><div className="mt-5 grid gap-4 lg:grid-cols-2"><div><h3 className="mb-2 flex items-center gap-2 font-bold"><BookOpen size={16}/> Trading diary</h3><Timeline items={[`Entry från ${pos.engine_label}, ${pos.side} @ ${Number(pos.avg_entry_price).toFixed(2)}`,`Signal/outcome följs i journalen. ${related.length} relaterade journalrader hittade.`,`Invalidation vid stop-loss. Detta är utbildning, inte investeringsråd.`]}/></div><div><h3 className="mb-2 font-bold">Senaste symbol-journal</h3><DataTable rows={related} cols={['timestamp','label','status','pnl']}/></div></div></>}</motion.div></Dialog.Content></Dialog.Portal></Dialog.Root>}
function Chart({pos}){
  const canvas=useRef(null); const [tf,setTf]=useState('5Min'); const [err,setErr]=useState('');
  useEffect(()=>{let alive=true; setErr('');
    fetch(`/api/bars?symbol=${encodeURIComponent(pos.symbol)}&timeframe=${tf}&limit=180&v=${Date.now()}`,{cache:'no-store'})
      .then(r=>{if(!r.ok)throw Error('bars '+r.status);return r.json()})
      .then(d=>{if(alive) drawProChart(canvas.current,d.bars||[],pos,setErr)})
      .catch(e=>alive&&setErr(String(e.message||e)));
    const on=()=>drawProChart(canvas.current,window.__lastBars||[],pos,setErr); window.addEventListener('resize',on);
    return()=>{alive=false; window.removeEventListener('resize',on)};
  },[pos,tf]);
  return <div className="mt-4"><div className="mb-2 flex items-center justify-between gap-2"><div className="flex gap-2">{['5Min','15Min','1Hour','1Day'].map(x=><Button key={x} active={tf===x} onClick={()=>setTf(x)}>{x.replace('Min','m').replace('Hour','h').replace('Day','d')}</Button>)}</div><span className="text-xs text-slate-500">Candles ? axes ? SL/TP/entry ? volume</span></div><canvas ref={canvas} className="h-[390px] w-full rounded-2xl border border-slate-800 bg-slate-950 shadow-inner shadow-cyan-950/20"/>{err&&<div className="mt-2 rounded-xl border border-rose-500/30 bg-rose-500/10 p-2 text-sm text-rose-200">Chart: {err}</div>}</div>
}
function drawProChart(canvas,bars,pos,setErr){
  if(!canvas)return; window.__lastBars=bars; const dpr=window.devicePixelRatio||1,w=Math.max(700,canvas.clientWidth*dpr),h=390*dpr; canvas.width=w; canvas.height=h; const ctx=canvas.getContext('2d'); ctx.clearRect(0,0,w,h);
  const bg=ctx.createLinearGradient(0,0,0,h); bg.addColorStop(0,'#081124'); bg.addColorStop(1,'#030712'); ctx.fillStyle=bg; ctx.fillRect(0,0,w,h);
  const clean=(bars||[]).map(b=>({o:+b.o,h:+b.h,l:+b.l,c:+b.c,v:+(b.v||0),t:b.t})).filter(b=>Number.isFinite(b.c));
  if(!clean.length){setErr?.('Inga candles returnerades f?r '+pos.symbol); return;}
  setErr?.(''); const entry=+pos.avg_entry_price,cur=+pos.current_price,sl=+(pos.stop_loss||0),tp=+(pos.take_profit||0);
  const padL=58*dpr,padR=72*dpr,padT=24*dpr,padB=44*dpr,volH=54*dpr,chartH=h-padT-padB-volH,gap=10*dpr;
  const prices=clean.flatMap(b=>[b.h,b.l]).concat([entry,cur,sl,tp].filter(Boolean)); let min=Math.min(...prices),max=Math.max(...prices); const span=(max-min)||1; min-=span*.12; max+=span*.12;
  const x=i=>padL+i*(w-padL-padR)/Math.max(clean.length-1,1), y=v=>padT+(max-v)/(max-min)*(chartH-gap), vy=v=>padT+chartH+gap+(1-v/Math.max(...clean.map(b=>b.v),1))*volH;
  ctx.strokeStyle='rgba(148,163,184,.10)'; ctx.lineWidth=1*dpr; ctx.font=`${11*dpr}px Inter, system-ui`; ctx.fillStyle='#94a3b8';
  for(let i=0;i<5;i++){const yy=padT+i*(chartH-gap)/4,price=max-(max-min)*i/4; ctx.beginPath();ctx.moveTo(padL,yy);ctx.lineTo(w-padR,yy);ctx.stroke();ctx.fillText('$'+price.toFixed(cur<10?4:2),w-padR+8*dpr,yy+4*dpr)}
  for(let i=0;i<6;i++){const xx=padL+i*(w-padL-padR)/5; ctx.beginPath();ctx.moveTo(xx,padT);ctx.lineTo(xx,padT+chartH+volH);ctx.stroke();}
  const cw=Math.max(3*dpr,(w-padL-padR)/clean.length*.62);
  clean.forEach((b,i)=>{const xx=x(i),up=b.c>=b.o,col=up?'#22c55e':'#fb7185'; ctx.fillStyle=col+'55'; ctx.fillRect(xx-cw/2,vy(b.v),cw,padT+chartH+gap+volH-vy(b.v)); ctx.strokeStyle=col;ctx.fillStyle=col;ctx.lineWidth=1.3*dpr;ctx.beginPath();ctx.moveTo(xx,y(b.l));ctx.lineTo(xx,y(b.h));ctx.stroke();const yy=Math.min(y(b.o),y(b.c)),hh=Math.max(2*dpr,Math.abs(y(b.o)-y(b.c)));ctx.fillRect(xx-cw/2,yy,cw,hh)});
  function line(v,color,label,dashed=true){if(!v)return; const yy=y(v); ctx.strokeStyle=color; ctx.lineWidth=1.5*dpr; if(dashed)ctx.setLineDash([7*dpr,5*dpr]); ctx.beginPath();ctx.moveTo(padL,yy);ctx.lineTo(w-padR,yy);ctx.stroke();ctx.setLineDash([]); ctx.fillStyle=color; ctx.font=`bold ${12*dpr}px Inter`; ctx.fillText(`${label} $${v.toFixed(cur<10?4:2)}`,padL+8*dpr,yy-7*dpr); ctx.fillStyle=color+'22'; ctx.fillRect(w-padR+4*dpr,yy-12*dpr,64*dpr,20*dpr); ctx.fillStyle=color; ctx.fillText(v.toFixed(cur<10?4:2),w-padR+8*dpr,yy+4*dpr)}
  line(tp,'#f59e0b','TP'); line(entry,pos.side==='short'?'#fb7185':'#22c55e',`ENTRY ${pos.side.toUpperCase()}`); line(cur,'#e2e8f0','NOW'); line(sl,'#f43f5e','SL');
  ctx.fillStyle='#64748b'; ctx.font=`${11*dpr}px Inter`; ctx.fillText(clean[0].t?.slice(5,16).replace('T',' '),padL,h-16*dpr); ctx.fillText(clean.at(-1).t?.slice(5,16).replace('T',' '),w-padR-90*dpr,h-16*dpr);
}

createRoot(document.getElementById('root')).render(<App/>);
